apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: grafana-deployment 
  labels: 
    app: grafana 
    purpose: monitoring-demo 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: grafana 
      purpose: monitoring-demo 
  template: 
    metadata: 
      labels: 
        app: grafana 
        purpose: monitoring-demo 
    spec: 
      containers: 
      - name: grafana 
        image: grafana/grafana 
---
kind: Service 
apiVersion: v1 
metadata: 
  name: grafana-svc 
spec: 
  type: NodePort 
  selector: 
    app: grafana 
    purpose: monitoring-demo 
  ports: 
  - name: grafanaui 
    protocol: TCP 
    port: 3003 
    targetPort: 3000 